[package]
name = "red4lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5"
fnv = "1.0"
csv = "1.3"

[build-dependencies.cmake]
version = "0.1"
