name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: unzip resources
        run: |
          cd src
          Expand-Archive -Path .\metadata-resources.zip -DestinationPath .\
      
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: test
